# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: graph_loom.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'graph_loom.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10graph_loom.proto\x12\ngraph_loom\"\x8f\x01\n\x0cQueryRequest\x12\r\n\x05query\x18\x01 \x01(\t\x12\x34\n\x06params\x18\x02 \x03(\x0b\x32$.graph_loom.QueryRequest.ParamsEntry\x12\x0b\n\x03log\x18\x03 \x01(\x08\x1a-\n\x0bParamsEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\"\x8b\x01\n\rQueryResponse\x12\"\n\x04rows\x18\x01 \x03(\x0b\x32\x14.graph_loom.QueryRow\x12\x16\n\x0e\x61\x66\x66\x65\x63ted_nodes\x18\x02 \x01(\x04\x12\x1e\n\x16\x61\x66\x66\x65\x63ted_relationships\x18\x03 \x01(\x04\x12\x0f\n\x07mutated\x18\x04 \x01(\x08\x12\r\n\x05\x65rror\x18\x05 \x01(\t\"v\n\x08QueryRow\x12 \n\x04node\x18\x01 \x01(\x0b\x32\x10.graph_loom.NodeH\x00\x12\x30\n\x0crelationship\x18\x02 \x01(\x0b\x32\x18.graph_loom.RelationshipH\x00\x12\x0e\n\x04info\x18\x03 \x01(\tH\x00\x42\x06\n\x04item\"\x84\x01\n\x04Node\x12\n\n\x02id\x18\x01 \x01(\t\x12\r\n\x05label\x18\x02 \x01(\t\x12\x30\n\x08metadata\x18\x03 \x03(\x0b\x32\x1e.graph_loom.Node.MetadataEntry\x1a/\n\rMetadataEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\"\xb4\x01\n\x0cRelationship\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0f\n\x07\x66rom_id\x18\x02 \x01(\t\x12\r\n\x05to_id\x18\x03 \x01(\t\x12\r\n\x05label\x18\x04 \x01(\t\x12\x38\n\x08metadata\x18\x05 \x03(\x0b\x32&.graph_loom.Relationship.MetadataEntry\x1a/\n\rMetadataEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\x32N\n\nGraphQuery\x12@\n\x07\x45xecute\x12\x18.graph_loom.QueryRequest\x1a\x19.graph_loom.QueryResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'graph_loom_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_QUERYREQUEST_PARAMSENTRY']._loaded_options = None
  _globals['_QUERYREQUEST_PARAMSENTRY']._serialized_options = b'8\001'
  _globals['_NODE_METADATAENTRY']._loaded_options = None
  _globals['_NODE_METADATAENTRY']._serialized_options = b'8\001'
  _globals['_RELATIONSHIP_METADATAENTRY']._loaded_options = None
  _globals['_RELATIONSHIP_METADATAENTRY']._serialized_options = b'8\001'
  _globals['_QUERYREQUEST']._serialized_start=33
  _globals['_QUERYREQUEST']._serialized_end=176
  _globals['_QUERYREQUEST_PARAMSENTRY']._serialized_start=131
  _globals['_QUERYREQUEST_PARAMSENTRY']._serialized_end=176
  _globals['_QUERYRESPONSE']._serialized_start=179
  _globals['_QUERYRESPONSE']._serialized_end=318
  _globals['_QUERYROW']._serialized_start=320
  _globals['_QUERYROW']._serialized_end=438
  _globals['_NODE']._serialized_start=441
  _globals['_NODE']._serialized_end=573
  _globals['_NODE_METADATAENTRY']._serialized_start=526
  _globals['_NODE_METADATAENTRY']._serialized_end=573
  _globals['_RELATIONSHIP']._serialized_start=576
  _globals['_RELATIONSHIP']._serialized_end=756
  _globals['_RELATIONSHIP_METADATAENTRY']._serialized_start=526
  _globals['_RELATIONSHIP_METADATAENTRY']._serialized_end=573
  _globals['_GRAPHQUERY']._serialized_start=758
  _globals['_GRAPHQUERY']._serialized_end=836
# @@protoc_insertion_point(module_scope)
